# Generated by Django 2.1.4 on 2020-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0004_auto_20200122_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='qbdtask',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='qb_type',
            field=models.CharField(choices=[('QBFS', 'QBFS'), ('QBPOS', 'QBPOS'), ('QBO', 'QBO')], default='QBPOS', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realm',
            name='qbpos_company_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='qbpos_computer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='qbpos_version',
            field=models.CharField(blank=True, default='18', max_length=100, null=True),
        ),
    ]
