# Generated by Django 2.1.4 on 2020-05-26 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0005_auto_20200515_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbdtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
